load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "calculator",
    srcs = ["Calculator.cpp"],
    hdrs = ["Calculator.h"],
    strip_include_prefix = ".",
    visibility = ["//visibility:public"],
)
